spring:
  datasource:
    url: jdbc:mysql://localhost:3306/drive_assured?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    host: 124.222.111.81
    port: 369
    password: 369yun6379
    database: 8

# 打印SQL语句和结果集，本地开发环境可开启，线上注释掉
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 文件上传相关配置
file:
  # 本地上传服务配置
  local:
    # 上传文件访问路径
    access-path: /file/**
    # 上传文件保存路径，注意：最后带上反斜杠
    upload-path: /Users/mrliu/upload/boot/
    # 上传文件访问URL前缀
    access-url: http://localhost:8888/api/file

# 日志配置，logback-spring.xml中会引用以下变量
logback-spring:
  # 日志文件目录
  path: logs

